app/screens/home/bottomTabs/ChildDevelopment.tsx

- Checked milestones moved at bottom.

Checked milestones moved

---

app/components/homeScreen/BabyNotification.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/EditParentDetails.tsx
app/screens/home/EditChildProfile.tsx
app/services/childCRUD.ts

Child bug solving

---

app/components/LoadingScreenComponent.tsx
app/components/shared/ButtonGlobal.tsx
app/components/shared/ButtonView.tsx
app/components/shared/Icon.tsx
app/components/shared/LoadingStyle.tsx
app/components/shared/WalkthroughStyle.tsx
app/components/shared/radio.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/screens/localization/CountrySelection.tsx
app/screens/localization/LanguageSelection.tsx

iOS UI changes fixes

---

app/redux/sagaMiddleware/saga.ts
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/services/commonApiService.ts

changes in saga as per activechild

changes in saga as per activechild

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/database/dbquery/userRealmCommon.ts
app/database/schema/ChildDataSchema.ts
app/screens/home/HealthCheckups.tsx
app/screens/vaccination/AddReminder.tsx
app/services/healthCheckupService.ts

reminders module implementation for vaccination and health checkup

reminders module 

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx

auto delete reminder on module load if date is passed

reminder delete

---

app/assets/translations/appOfflineData/apiConstants.ts
app/components/shared/RelatedArticles.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Articles.tsx

- Added filter in Article screen fro categories.
- Added Related article conditions
- Similar changes in Details screen.

Related article conditions

---

app/components/vaccination/tabs/PreviousVaccines.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/home/DetailsScreen.tsx

detail screen linkage to vaccines

detail screen linkage to vaccines

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx

patch for fromMillis if no reminder added

if no reminder added condition

---

app/components/AgeBrackets.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
modifiedModules/react-native-scroll-menu/index.js

child development age brackets UI fixed

child development UI fixed

---

app/redux/store.ts
app/services/childCRUD.ts

Child devtool milestone

---

app/components/ChildDate.tsx
app/components/homeScreen/BabyNotification.tsx
app/components/shared/ButtonGlobal.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx
app/services/Utils.ts
app/services/childCRUD.ts

1.Addexpectingchild edit changes

1.Addexpectingchild edit changes

---

app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/PlannedVaccines.tsx
app/components/vaccination/PrevPlannedVaccines.tsx
app/components/vaccination/VaccineItem.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/DetailsScreen.tsx
app/screens/vaccination/AddChildVaccination.tsx

go to details linked for articles and health checkup

go to details linked for articles and health checkup

---

app/components/vaccination/PlannedVaccines.tsx
app/components/vaccination/PrevPlannedVaccines.tsx

issue fixed for marking multiple  vaccines in add vaccination

issue fixed for marking multiple  vaccines in add vaccination

---

app/assets/translations/appConstants/en.ts
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/HealthCheckups.tsx
app/screens/home/Vaccination.tsx
app/services/vacccineService.ts

no data conditions for HC and VC

no data conditions for HC and VC

---

app/assets/translations/appConstants/en.ts
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx

removed edit access to HC

---

app/components/vaccination/PrevPlannedVaccines.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/vaccination/AddChildVaccination.tsx

commented delete button on HC,VC
added text for no prev plaaned vaccine

added text for no prev plaaned vaccine

---

app/components/growth/LastChildMeasure.tsx
app/screens/home/Childgrowth.tsx

removed extra article on growth

removed extra article on growth

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/PreviousVaccines.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx

Vaccination, Health Check up Icon for iOS UI issue fixed

iOS UI issue fixed

---

app/components/growth/ActiveChildMeasureTimeline.tsx
app/components/growth/GrowthIntroductory.tsx
app/components/growth/LastChildMeasure.tsx
app/navigation/DashboardTabNavigator.tsx
app/navigation/HomeDrawerNavigator.tsx
app/screens/growth/ChartFullScreen.tsx
app/services/healthCheckupService.ts
app/services/vacccineService.ts

fixes for unmount

---

app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/growth/LastChildMeasure.tsx
app/screens/growth/AddNewChildgrowth.tsx

growth issue fixture

---

app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/vaccination/AddChildVaccination.tsx

measure forms edit issue resolved

measure forms edit issue resolved

---

app/services/healthCheckupService.ts
app/services/vacccineService.ts

fixed vaccine and hc service functions

fixed vaccine and hc service functions

---

app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/growth/GrowthIntroductory.tsx
app/components/growth/LastChildMeasure.tsx
app/components/shared/FlexBoxStyle.tsx
app/screens/growth/ChartFullScreen.tsx

growth full screen UI changes

---

app/assets/translations/appConstants/en.ts
app/components/growth/LastChildMeasure.tsx
app/database/dbquery/userRealmCommon.ts
app/screens/AddExpectingChildProfile.tsx
app/screens/ChildSetupList.tsx
app/screens/EditParentDetails.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/EditChildProfile.tsx
app/services/childCRUD.ts

1.performance changes
2.en changes

performance changes

---

app/assets/translations/appOfflineData/apiConstants.ts
app/components/ActivitiesCategories.tsx
app/components/AgeBrackets.tsx
app/components/ArticleCategories.tsx
app/components/shared/RelatedActivities.tsx
app/database/schema/ActivitiesSchema.ts
app/navigation/AppNavigation.tsx
app/navigation/DashboardTabNavigator.tsx
app/navigation/types.ts
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx

- Worked on creating dynamic list in activities screen.
- Worked on Details screen condition for activities.
- Created Related Activity screen and implemented condition as required for activity.
- Solved Child Development issue on back button.
- Hided the i icon if no video article in Child Development.

Activities dynamic data

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/screens/vaccination/AddReminder.tsx

reminder timing solved

---

app/services/childCRUD.ts

sorted code

---

.gitignore

commited gitignore

---

app/components/VideoPlayer.tsx

autoplay off

---

.gitignore
android/app/build.gradle
app/assets/translations/appOfflineData/taxonomies.ts
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/VaccineItem.tsx
app/components/vaccination/tabs/PreviousVaccines.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/vaccination/AddReminder.tsx
app/services/healthCheckupService.ts

fixes on HC and VC module, taxonomy form api added

fixes on HC and VC module, taxonomy form api added

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/components/HeaderBabyMenu.tsx
app/components/homeScreen/ChildInfo.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/MediaPicker.ts
app/services/childCRUD.ts

1.welcome parent changes.
2.Permission changes,photo minor bugs.
3.show photo in top right and menu.

bug solving

---

app/components/ChildDate.tsx
app/components/HeaderBabyMenu.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetup.tsx
app/screens/home/EditChildProfile.tsx

dobmax changes
scroll issue solved

dobmax changes scroll issue solved

---

app/assets/translations/appOfflineData/getDataToStore.ts
app/components/AgeBrackets.tsx
app/components/homeScreen/ChildInfo.tsx
app/components/shared/RelatedArticles.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/services/index.js
package-lock.json
package.json

- Solved agebrackets issue.
- Hide child info module in Home page if no data.
- Added logic for maintaining age bracket and selected category after coming back.
- Added agebracket in service and removed module.
- On tabs change reset page params.

Activities details

---

app/components/ActivitiesCategories.tsx
app/components/ChildDate.tsx
app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/growth/GrowthChart.tsx
app/components/growth/GrowthIntroductory.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/FilterStyle.tsx
app/components/shared/FormPrematureContainer.tsx
app/components/shared/RelatedArticles.tsx
app/screens/ChildSetup.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

Articles, Activities, Child Growth, Child Setup UI fixes

Articles, Activities, Child Growth, Child Setup UI fixes

---

app/screens/home/EditChildProfile.tsx

dobmax till new date added

---

app/screens/home/EditChildProfile.tsx

editprofile uri null condition check

editprofile uri null condition check

---

app/components/homeScreen/BabyNotification.tsx
app/screens/home/Childgrowth.tsx

1.child image added in babyheader icon

child image added in babyheader icon

---

.gitignore
android/gradle.properties
app/components/HeaderBabyMenu.tsx
app/customHooks/useDoubleBackPressExit.ts
app/navigation/DashboardTabNavigator.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/healthCheckupService.ts
app/services/vacccineService.ts

taxonomy changes revert to main

taxonomy and back handler for home

---

app/assets/translations/appConstants/en.ts
app/components/OverlayLoadingComponent.tsx
app/components/shared/FirstTimeModal.tsx
app/components/shared/InfiniteScrollList.tsx
app/redux/reducers/utilsSlice.ts
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/screens/localization/LanguageSelection.tsx
app/services/index.js
package-lock.json
package.json

- Added html table module for tables in body.
- Created First time message modal common component.
- Added firsttime component in Activity and Child Dev module.
- Made changes for loading overlay in article module.
- Solved article infinite loop issue on active child change.
- On confirmation screen changed the language as selected from language screen.

Solved issues

---

app/components/HeaderBabyMenu.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/services/healthCheckupService.ts

HC , vc icon issue resolved and Headerbabymeu structre changed

HC , vc icon issue resolved and Headerbabymeu structre changed

---

app/components/HeaderBabyMenu.tsx
app/screens/ChildSetup.tsx
app/screens/ChildSetupList.tsx
app/screens/home/ChildProfile.tsx

Header dropdown, child setup list design fixed

Header dropdown, child setuplist design fixed

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/assets/translations/appOfflineData/apiConstants.ts
app/services/childCRUD.ts

1.plural changes in translatio

1.plural changes in translatio

---

app/assets/translations/appOfflineData/apiConstants.ts

api changes

---

modifiedModules/Readme.txt

modified_Modules added

---

app/screens/home/SettingScreen.tsx

edit icon disabled

---

app/components/HeaderBabyMenu.tsx
app/services/childCRUD.ts

agebracket changes

---

app/components/HeaderBabyMenu.tsx

top list position fixed

---

app/assets/translations/appConstants/en.ts
app/components/growth/LastChildMeasure.tsx
app/components/shared/InfiniteScrollList.tsx
app/components/shared/RelatedActivities.tsx
app/components/shared/RelatedArticles.tsx
app/redux/reducers/utilsSlice.ts
app/redux/sagaMiddleware/saga.ts
app/redux/sagaMiddleware/sagaSlice.ts
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/screens/localization/CountrySelection.tsx
app/services/Utils.ts
app/services/commonApiService.ts
app/services/index.js

- Added image url condition for empty string
- Added data from language file in commonapiservice alerts
- Solved article loading issue.
- Solved activity blank data issue and related activity logic.
- Emptied error array on app start everytime.
- Minor changes in Saga files.

Bugs solving

---

app/components/shared/ArticlesStyle.tsx
app/components/shared/FormPrematureContainer.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/EditParentDetails.tsx

iOS issue fixed

---

app/assets/translations/appOfflineData/healthCheckupsData.ts
app/components/growth/ActiveChildMeasureTimeline.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/screens/home/HealthCheckups.tsx

HC Vc changes done

---

app/assets/translations/appConstants/en.ts
app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/growth/GrowthChart.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/navigation/AppNavigation.tsx
app/screens/growth/ChartFullScreen.tsx
app/screens/home/Aboutus.tsx
app/screens/home/Vaccination.tsx
app/screens/vaccination/AddChildVaccination.tsx

issues fixed

---

app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/growth/GrowthChart.tsx
app/screens/growth/ChartFullScreen.tsx

delay in reload of graph on orientation change

delay in reload of graph on orientation change

---

android/app/build.gradle
app/assets/data/localization.ts
app/components/ChildDate.tsx
app/components/HeaderBabyMenu.tsx
app/database/dbquery/dataRealmCommon.ts
app/redux/reducers/localizationSlice.ts
app/screens/AddExpectingChildProfile.tsx
app/screens/ChildSetup.tsx
app/screens/ChildSetupList.tsx
app/screens/CustomDrawerContent.tsx
app/screens/Terms.tsx
app/screens/home/ChildProfile.tsx
app/screens/localization/CountryLanguageConfirmation.tsx
app/screens/localization/CountrySelection.tsx
app/services/Utils.ts
index.js

added localization support for luxon

added localization support for luxon

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/screens/AddExpectingChildProfile.tsx

edit child profile added

---

app/screens/AddExpectingChildProfile.tsx

added string in english for edit expecting child

added string in english for edit expecting child

---

app/screens/localization/CountryLanguageConfirmation.tsx

language for serbia and english

language for serbia and english

---

app/components/ChilDevelopmentCollapsibleItem.tsx

Video pop up added

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/components/ChildDate.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetup.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx

translations for edit profile added

translations for edit profile added

---

app/assets/translations/appOfflineData/SurveyData.ts
app/assets/translations/appOfflineData/getDataToStore.ts
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/homeScreen/DailyHomeNotification.tsx
app/redux/reducers/utilsSlice.ts
app/screens/home/bottomTabs/Home.tsx
app/services/healthCheckupService.ts

HC update for periods, modal for home survey

HC update for periods

---

app/components/HeaderBabyMenu.tsx

set modal false on manage profile click

set modal false on manage profile click

---

app/screens/AddExpectingChildProfile.tsx
app/screens/EditParentDetails.tsx

textinput style 100%

---

app/screens/home/ChildProfile.tsx

e.stoppropagation

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/shared/ModalPopupStyle.tsx

child development video UI design fixed

child development video UI design fixed

---

app/components/shared/ModalPopupStyle.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/home/EditChildProfile.tsx

child profile UI changes fixed

child profile UI changes fixed

---

app/components/shared/InfiniteScrollList.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

Article Issues Solved

---

app/components/shared/RelatedActivities.tsx

Name Change in activity

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx

- Modal hide condition changed little.
- added a minor change for image in child dev.

Minor changes

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/RSsr.ts
app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/homeScreen/ChildInfo.tsx
app/screens/Terms.tsx

Changes for image in dev page.
added some missing strings in 2 files.

Changes for collapsible

---

app/components/growth/ChartHeightForAge.tsx
app/components/growth/GrowthChart.tsx
app/components/shared/Icon.tsx
app/components/shared/TrackMilestoneView.tsx
app/components/vaccination/PlannedVaccines.tsx
app/components/vaccination/PrevPlannedVaccines.tsx
app/components/vaccination/VaccineItem.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/growth/ChartFullScreen.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/bottomTabs/Home.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

fixed issues in Child Growth, Vaccination, Healthcheckup

fixed issues in Child Growth, Vaccination, Healthcheckup

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/screens/home/bottomTabs/Home.tsx

- Solved firsttimemodal popup issue in all 3 modules.
- Hide activity div in childdev if no data.

Minor bugs

---

app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/en.ts
app/components/homeScreen/ChildInfo.tsx
app/screens/AddExpectingChildProfile.tsx

-expected date change
- Minor text changes.
Co-Authored-By: Kalyani790 <82521546+Kalyani790@users.noreply.github.com>

expected date change

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/growth/ChartWeightForHeight.tsx
app/components/shared/ModalPopupStyle.tsx

child devt ui changes fixed

---

app/components/growth/ActiveChildMeasureTimeline.tsx
app/components/growth/LastChildMeasure.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/PreviousVaccines.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx
app/services/Utils.ts
app/services/healthCheckupService.ts

date changes

---

app/components/growth/ActiveChildMeasureTimeline.tsx
app/screens/home/DetailsScreen.tsx
app/screens/vaccination/AddChildVaccination.tsx

add useAppselector
crash issue
add vaccination crash

add useAppselector crash issue add vaccination crash

---

app/components/ChildDate.tsx
ios/ParentBuddyApp/LaunchScreen.storyboard

launchscreen changes

---

app/components/HeaderBabyMenu.tsx
app/components/growth/ChartWeightForHeight.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/services/StatusBarHeight.ts

header changes
statusbar height added

statusbar height added

---

app/screens/growth/AddNewChildHeight.tsx
app/screens/growth/AddNewChildWeight.tsx

flikker popup resolved

---

app/components/ChildDate.tsx
app/components/growth/ChartHeightForAge.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/shared/FormPrematureContainer.tsx
app/components/shared/ModalPopupStyle.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/HealthCheckups.tsx

UI issues fixes on Child Setup, Health check up, child growth

UI issues fixes on Child Setup, Health check up, child growth,

---

app/components/shared/InfiniteScrollList.tsx
app/navigation/DashboardTabNavigator.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

- Activity no data issue solved.
- Scroll to top added in activity.
- On back dont refresh data code added in article and activity screen.

Minor bugs solved

---

app/screens/vaccination/AddReminder.tsx

reminder time changes

---

app/components/VideoPlayer.tsx

Video player spacing issue fixed

Video player spacing issue fixed

---

app/components/HeaderBabyMenu.tsx
app/components/VideoPlayer.tsx

babymenyu height
videoplayer auto play

babymenyu height

---

app/screens/vaccination/AddReminder.tsx

Add reminder issue fixed in iOS

Add reminder issue fixed in iOS

---

app/components/growth/GrowthChart.tsx
app/screens/growth/ChartFullScreen.tsx

growth chart landscape issue fixed

growth chart landscape issue fixed

---

app/components/VideoPlayer.tsx

youtube loader changes

---

app/components/shared/ModalPopupStyle.tsx

flex1 added

---

app/screens/home/bottomTabs/Articles.tsx

download image added

---

app/components/shared/InfiniteScrollList.tsx
app/components/shared/RelatedActivities.tsx
app/components/shared/RelatedArticles.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/vaccination/AddReminder.tsx
app/services/LoadableImage.tsx

loadingImage change

---

app/screens/Terms.tsx
app/screens/vaccination/AddReminder.tsx
app/services/LoadableImage.tsx

changes for reminder date

---

app/components/VideoPlayer.tsx

videoplayer inline vimeo

---

app/components/shared/RelatedActivities.tsx
app/components/shared/RelatedArticles.tsx
app/screens/Terms.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/services/LoadableImage.tsx

- Flatlist performance optimisation code added.
- Loadable multiple calls issue solved.

Flatlist performance optimised

---

app/components/VideoPlayer.tsx

crash issue solved

---

app/components/VideoPlayer.tsx

videoplayer issue

---

app/components/HeaderBabyMenu.tsx
app/components/growth/ActiveChildMeasureTimeline.tsx
app/components/growth/LastChildMeasure.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/homeScreen/AdviceAndArticles.tsx
app/components/homeScreen/BabyNotification.tsx
app/components/homeScreen/ChildInfo.tsx
app/components/homeScreen/ChildMilestones.tsx
app/components/homeScreen/PlayingTogether.tsx
app/components/shared/ButtonGlobal.tsx
app/components/shared/FirstTimeModal.tsx
app/components/shared/TrackMilestoneView.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/CustomDrawerContent.tsx
app/screens/growth/AddNewChildHeight.tsx
app/screens/growth/AddNewChildWeight.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/Notifications.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/home/bottomTabs/Home.tsx

button changes fixed for text flexibility

button changes fixed for text flexibility

---

app/components/VideoPlayer.tsx

video player issue fixed

---

app/navigation/AppNavigation.tsx
app/screens/home/bottomTabs/Activities.tsx

- Solved article crash issue by disabling animation on stack.
- Added sectionlist in activity screen and solved back scroll issue.

Article and Activity issue

---

app/navigation/AppNavigation.tsx

changes added for ios animation

changes added for ios animation

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/HeaderBabyMenu.tsx
app/components/NotificationItem.tsx
app/components/healthChekup/PreviousHealthCheckup.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/shared/ShareFavButtons.tsx
app/components/shared/TabBarStyle.tsx
app/components/vaccination/tabs/PreviousVaccines.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetupList.tsx
app/screens/EditParentDetails.tsx
app/screens/Walkthrough.tsx
app/screens/growth/AddNewChildHeight.tsx
app/screens/growth/AddNewChildWeight.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/growth/AllChildgrowthMeasures.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/Favourites.tsx
app/screens/home/HealthCheckups.tsx
app/screens/home/Vaccination.tsx
app/screens/localization/CountryLanguageConfirmation.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

text link, tabs restricted till 2lines fixed

text link, tabs restricted till 2lines fixed

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/shared/Icon.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/vaccination/AddReminder.tsx

iOS reminder icon issue fixed

---

app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx

- Age bracket cache issue solved.

Age bracket cache issue

---

app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

- Activity loading added and issue solved.
- Article added one condition.

Activity, Article issues solved

---

app/navigation/AppNavigation.tsx
app/screens/home/Notifications.tsx

navigation event analytics updated

navigation event analytics updated

---

app/components/ToggleRadios.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/Container.tsx
app/components/shared/NavigationDrawer.tsx
app/components/shared/ToolsStyle.tsx
app/components/shared/WalkthroughStyle.tsx
app/components/shared/radio.tsx
app/components/vaccination/VaccineItem.tsx
app/screens/CustomDrawerContent.tsx
app/screens/Walkthrough.tsx
app/screens/home/Vaccination.tsx

text wrapping, overlapping issues fixed

UI issues fixed

---

app/assets/translations/appOfflineData/article.ts

- Article offline data changed

Article offline data changed

---

app/components/ActivitiesCategories.tsx
app/components/ArticleCategories.tsx
app/components/shared/ShareFavButtons.tsx
app/navigation/AppNavigation.tsx
app/screens/ChildSetupList.tsx
app/screens/CustomDrawerContent.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/Notifications.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/ChildDevelopment.tsx
app/screens/home/bottomTabs/Home.tsx
app/screens/localization/CountryLanguageConfirmation.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx
app/services/childCRUD.ts

async await removed for analytics

async await removed for analytics

---

app/components/shared/ButtonGlobal.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/Container.tsx
app/components/shared/Divider.tsx
app/components/vaccination/VaccineItem.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/ChildSetupList.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

bug fixed in child module, add reminder, vaccination

bug fixed in child module, add reminder, vaccination

---

app/components/ActivitiesCategories.tsx
app/components/ArticleCategories.tsx
app/components/growth/GrowthChart.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/FilterStyle.tsx
app/screens/ChildSetupList.tsx
app/screens/CustomDrawerContent.tsx

child list ui fixed, activity filter ui spacing issue fixed child growth chart height set in portrait,

child list, activity, child growth

---

app/assets/translations/appOfflineData/getDataToStore.ts
app/navigation/AppNavigation.tsx
app/redux/reducers/utilsSlice.ts
app/redux/sagaMiddleware/saga.ts
app/redux/sagaMiddleware/sagaActions.ts
app/redux/sagaMiddleware/sagaSlice.ts
app/screens/LoadingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

- Api error download pop up added on app start.
- Made changes for same in different files.
- Removed db listeners.

App start pop up added

---

app/components/LoadingScreenComponent.tsx
app/redux/reducers/localizationSlice.ts
app/redux/sagaMiddleware/saga.ts
app/services/commonApiService.ts

sponsars code changed

---

app/screens/EditParentDetails.tsx

edit parent details

---

app/assets/translations/appConstants/XKrs.ts

language change

---

app/components/shared/ChildSetupStyle.tsx
app/components/shared/ShareFavButtons.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/growth/AllChildgrowthMeasures.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/vaccination/AddChildVaccination.tsx

minor UI issues fixes on child module, share fav , add vaccination & health checkup

child module, share fav , add vaccination & health checkup

---

app/assets/translations/appOfflineData/getDataToStore.ts
app/redux/sagaMiddleware/saga.ts
app/screens/ChildSetupList.tsx
app/screens/LoadingScreen.tsx
app/screens/home/SettingScreen.tsx
app/screens/localization/CountryLanguageConfirmation.tsx
app/screens/localization/CountrySelection.tsx
app/services/childCRUD.ts

- Made changes for calling all api's on country change

country language change

---

app/screens/home/bottomTabs/Activities.tsx

iOS scroll issue

---

app/assets/data/localization.ts

en-Us added

---

app/screens/home/bottomTabs/Activities.tsx

Minor change

---

app/assets/customLocale/bg-BG.js
app/components/homeScreen/ChildInfo.tsx
app/services/Utils.ts
index.js

changes for bg-BG

---

app/assets/customLocale/tg-TJ.js
index.js

tajik file added

---

app/redux/reducers/realmPersistor.js
app/screens/localization/CountrySelection.tsx

changes for active child change crash
sponsars image old display issue

changes for active child change crash sponsars image old display issue

---

app/screens/LoadingScreen.tsx

settings sponsars logo deleted

settings sponsars logo deleted

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/screens/vaccination/AddReminder.tsx
app/services/interpretationService.ts

alert added for saving past date in reminder

alert added for saving past date in reminder

---

app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx

hide passed reminders on vc hc,display till current minute are passed

hide passed reminders on vc hc,display till current minute are passed

---

app/components/growth/LastChildMeasure.tsx

Old Growth notification design implement

Old Growth notification design implement

---

app/screens/home/SettingScreen.tsx

formatstring date on settings screen

formatstring date on settings screen

---

app/screens/home/EditChildProfile.tsx

edit profile - action sheet UI fixed

edit profile - action sheet UI fixed

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/LoadingScreenComponent.tsx
app/components/VideoPlayer.tsx
app/components/shared/ModalPopupStyle.tsx

video cut issue, loading screen logo issue fixed

video cut issue, loading screen logo issue,

---

app/screens/vaccination/AddChildVaccination.tsx

Added  multiline={true} and maxLength={maxCharForRemarks}

Add Vaccination textArea

---

android/app/build.gradle
app/screens/growth/AddNewChildgrowth.tsx

update for vaccine and growth date change is done

update for vaccine and growth date change is done

---

app/database/config/dbConfig.ts
app/database/dbquery/userRealmCommon.ts
app/database/migration/init.ts
app/screens/home/SettingScreen.tsx
app/services/Utils.ts
app/services/backup.tsx
app/services/googleAuth.ts
app/services/googleDrive.ts

changes for drive import export

changes for drive import export

---

app/components/HeaderBabyMenu.tsx
app/components/homeScreen/DailyReads.tsx
app/navigation/AppNavigation.tsx
app/redux/reducers/articlesSlice.ts
app/screens/ChildSetupList.tsx
app/screens/home/ChildProfile.tsx
app/services/backup.tsx
app/services/childCRUD.ts

- Added functionality for Daily reads on Home screen.
- Active child taxonomy calculation change as given by kalyani.

Daily reads on home screen

---

app/components/NotificationItem.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/screens/home/Notifications.tsx
app/services/notificationService.ts

notification logic added from childAge,allHealthCheckupsData,allVaccinePeriods,allGrowthPeriods

notification logic added

---

app/components/homeScreen/DailyReads.tsx
app/redux/reducers/articlesSlice.ts

- Added no repeat random number functionality for each category.
- Implemented object in UI with loadable image.

Daily reads changes

---

app/components/vaccination/PlannedVaccines.tsx
app/database/dbquery/userRealmCommon.ts
app/screens/CustomDrawerContent.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/services/childCRUD.ts

delete old data while changing dob

delete old data while changing dob

---

app/screens/home/bottomTabs/Home.tsx

- Changes made for testing Periodic sync

Periodic Sync test

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/screens/home/SettingScreen.tsx

loader added oon settings screen

loader added oon settings screen

---

android/app/build.gradle
app/components/HeaderBabyMenu.tsx
app/database/dbquery/userRealmCommon.ts
app/navigation/AppNavigation.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/ChildSetupList.tsx
app/screens/EditParentDetails.tsx
app/screens/LoadingScreen.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/Utils.ts
app/services/backup.tsx
app/services/childCRUD.ts

datepicker on home multi time calling issue
import error

datepicker on home multi time calling issue import error

---

app/components/homeScreen/DailyReads.tsx
app/database/dbquery/userRealmCommon.ts
app/services/Utils.ts
app/services/healthCheckupService.ts

import of measures and reminders from gdrive fixed for old data file and new data file

import of measures and reminders from gdrive

---

app/components/homeScreen/DailyReads.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Home.tsx

- Solved Popup repeat occurrence issue.
- Added clicks on daily read for Detailscreen.
-

Daily reads click

---

app/assets/translations/appOfflineData/SurveyData.ts
app/components/NotificationItem.tsx
app/components/NotificationsCategories.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetup.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/Notifications.tsx
app/services/childCRUD.ts
app/services/notificationService.ts

updated for child createdat field changes

---

app/components/homeScreen/DailyReads.tsx

- Daily Reads activity data of current child condition added.

Daily reads

---

app/components/VideoPlayer.tsx
app/navigation/AppNavigation.tsx

videoplayed changes

---

android/app/build.gradle
app/customHooks/useNetInfoHook.ts
app/navigation/AppNavigation.tsx
app/screens/home/bottomTabs/Home.tsx

code committed

---

app/navigation/AppNavigation.tsx

remove network offline low bandwidth condition

remove network offline low bandwidth condition

---

app/components/homeScreen/ChildInfo.tsx
app/components/homeScreen/DailyReads.tsx
app/components/shared/HomeScreenStyle.tsx

home screen child info& daily reads design fixed

home screen child info& daily reads design fixed

---

app/screens/ChildSetupList.tsx
app/screens/home/bottomTabs/Home.tsx

changes for warning solved

---

app/screens/AddSiblingData.tsx

defaultname naming convention

---

app/components/homeScreen/DailyReads.tsx
app/screens/CustomDrawerContent.tsx

ternary added for key if not added

ternary added for key if not added

---

android/app/build.gradle
app/components/NotificationItem.tsx
app/navigation/AppNavigation.tsx
app/redux/reducers/utilsSlice.ts
app/screens/home/EditChildProfile.tsx
app/screens/home/Notifications.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/backup.tsx
app/services/childCRUD.ts
app/services/commonApiService.ts
app/services/notificationService.ts

changes for notifications commented

changes for notifications commented

---

app/screens/home/bottomTabs/Home.tsx

- Added useEffect instead of useMemo.
- Made modal false on 1st time home screen.

Added useEffect

---

app/navigation/AppNavigation.tsx

hide sync popup first time

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/shared/ModalPopupStyle.tsx

child development popup video close icon ui fixed

child development popupvideo close icon ui fixed

---

app/redux/reducers/index.ts
app/redux/sagaMiddleware/saga.ts
app/redux/sagaMiddleware/sagaActions.ts
app/redux/sagaMiddleware/sagaSlice.ts
app/screens/LoadingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

- Survey api called on everytime app open.
- Added conditions for same in saga.
- Added network check in api calls and added those api's in error object.

Survey api call

---

app/components/homeScreen/DailyReads.tsx
app/redux/reducers/articlesSlice.ts
app/services/commonApiService.ts

- Daily reads will be same on same date.
- Daily reads will be generated again on language change.

Daily reads conditions changed

---

app/screens/Walkthrough.tsx

heading font size reduces

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/redux/sagaMiddleware/saga.ts
app/screens/LoadingScreen.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

- Download update functionality implemented.
- strings added for same in all languages.
- On language change and periodic sync buffer data also downloaded.
- Weekly monthly date change uncommented from home screen

Download update functionality

---

app/components/shared/HomeScreenStyle.tsx

Update Daily tag homescreen

---

app/components/NotificationItem.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/Notifications.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/notificationService.ts

notification updates

---

app/components/ChilDevelopmentCollapsibleItem.tsx

- Expected child milestone click disabled

Expected child milestone click disabled

---

app/components/homeScreen/DailyReads.tsx
app/components/shared/RelatedArticles.tsx
app/downloadImages/ImageStorage.ts
app/screens/home/bottomTabs/Activities.tsx

- Download sponsor image issue solved

Download sponsor image issue solved

---

android/app/build.gradle
app/screens/vaccination/AddReminder.tsx

reminder 5 year max added

---

app/localization/initI18next.ts

postprocess trim whitespace

---

app/assets/translations/appConstants/en.ts
app/navigation/AppNavigation.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

low bandwidth changes

---

app/components/shared/Divider.tsx
app/components/shared/HeaderContainerStyle.tsx
app/components/shared/HomeScreenStyle.tsx
app/components/shared/ProfileListingStyle.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/bottomTabs/Home.tsx

manage profile changes, offline bar ui design

manage profile changes, offline bar ui design

---

app/screens/LoadingScreen.tsx
app/screens/localization/CountryLanguageConfirmation.tsx

- Sponsor logo issue solved.Conditions added.

Sponsor logo issue

---

app/components/homeScreen/DailyReads.tsx

Daily read crash issue

---

app/components/homeScreen/DailyReads.tsx
app/components/shared/RelatedActivities.tsx
app/components/shared/RelatedArticles.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

- Unused functionalities commented.

Unused functionalities commented

---

app/components/Ruler.tsx
app/screens/home/SettingScreen.tsx

Ruler and setting logic updated

Ruler and setting logic updated

---

app/services/commonApiService.ts

reject change to resolve

---

app/components/shared/SettingsStyle.tsx
app/screens/home/SettingScreen.tsx

setting screen toggle ui fixed

setting screen toggle ui fixed

---

app/screens/home/SettingScreen.tsx

Added internet check in settings screen

Added internet check in settings screen

---

app/screens/EditParentDetails.tsx

edit parent details validation

edit parent details validation

---

app/components/ChilDevelopmentCollapsibleItem.tsx
app/components/shared/ModalPopupStyle.tsx

popup video styling fixed

---

app/components/VideoPlayer.tsx

- Data saver video condition removed

Data saver video condition removed

---

app/screens/CustomDrawerContent.tsx
app/screens/home/bottomTabs/Home.tsx

Switch child profile deleted notification will come again in future  **resolved**

notification issue  for regeneration in future resolved

---

app/components/shared/HomeScreenStyle.tsx
app/components/shared/ProfileListingStyle.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/EditParentDetails.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/Notifications.tsx
app/screens/home/SettingScreen.tsx

Manage profile back button ui fixes, setting edit icon area increased

Manage profile back button ui fixes, setting edit icon area increased

---

app/assets/translations/appOfflineData/apiConstants.ts
app/services/growthService.ts
app/services/healthCheckupService.ts
app/services/measureUtils.ts
app/services/notificationService.ts

const update for modules

---

app/components/ChilDevelopmentCollapsibleItem.tsx

- Changes for video overlay in Child dev module

Changes for video overlay

---

app/assets/translations/appConstants/MKmk.ts

macedonian changes

---

app/components/ChilDevelopmentCollapsibleItem.tsx

- Changed design and added modal close conditions.

Modal changes

---

app/screens/home/bottomTabs/Home.tsx

Test buttons commented

---

app/assets/translations/appOfflineData/apiConstants.ts
app/screens/AddExpectingChildProfile.tsx
app/screens/EditParentDetails.tsx
app/screens/home/EditChildProfile.tsx

changes for adding multiple language characters

changes for adding multiple language characters

---

app/components/shared/ChildSetupStyle.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/screens/vaccination/AddChildVaccination.tsx

text box style update for doctor comment
childlist of get-children added with ? for data consistency

text box style update for doctor comment

---

app/components/homeScreen/DailyReads.tsx

- Daily reads refresh issue solved

Daily reads refresh issue solved

---

app/screens/home/ChildProfile.tsx

list scroll UI changes made

---

app/screens/localization/CountrySelection.tsx

- Language change on app start mismatch issue solved

Language change on app start mismatch

---

app/components/homeScreen/DailyReads.tsx
app/components/shared/HomeScreenStyle.tsx
app/screens/home/DetailsScreen.tsx

Daily Reads Homepage section height increased, clickable issue solved. Activity Details milestone banner extra spacing remvoed.

Daily Reads, Activity Details

---

app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/UZru.ts
app/screens/EditParentDetails.tsx
app/services/childCRUD.ts

changes for adding relationship

changes for adding relationship

---

app/screens/home/DetailsScreen.tsx

Details screen HTML tagsStyles updated

Details screen HTML tagsStyles updated

---

app/screens/ChildSetup.tsx
app/screens/EditParentDetails.tsx

changes for relationship changes

changes for relationship changes

---

app/screens/home/bottomTabs/Home.tsx

Hardware back issue solved

---

app/components/HeaderBabyMenu.tsx
app/components/shared/ButtonGlobal.tsx
app/components/shared/HomeScreenStyle.tsx
app/components/shared/NavigationDrawer.tsx
app/components/shared/ProfileListingStyle.tsx
app/screens/ChildSetupList.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/ChildProfile.tsx

clickable link/buttons issues fixed on homescreen, sidemenu, manageprofile screens.

clickable link/buttons issues fixed

---

app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

settimeout changed to 2500

---

app/navigation/AppNavigation.tsx
app/navigation/HomeDrawerNavigator.tsx
app/navigation/types.ts

Reverts UNICEFECAR/parenting-app-bebbo-mobile#619

Revert "child profile back swipe issue solved"

---

app/assets/translations/appConstants/MEcnr.ts
app/screens/AddSiblingData.tsx
app/screens/home/EditChildProfile.tsx

changes for bugs
nan bug in addsibling in serbian
montegring ageinmonth variable correction
childprofile photo remove bug

changes for bugs

---

app/screens/home/ChildProfile.tsx
app/screens/home/EditChildProfile.tsx

1.child profile list dynamic heght
2.edit profile header issue

1.child profile list dynamic heght 2.edit profile header issue

---

app/components/homeScreen/DailyReads.tsx
app/localization/initI18next.ts
app/redux/reducers/articlesSlice.ts
app/screens/localization/CountrySelection.tsx
app/services/commonApiService.ts

- Daily reads saved as per child.
- Daily reads bugs solved.
- Language as per device saved on start up
- Hardware back on walkthrough issue solved.

Bugs solved of Daily reads and Language

---

android/app/build.gradle
app/components/homeScreen/DailyReads.tsx
app/redux/reducers/articlesSlice.ts
app/services/commonApiService.ts

Daily reads saved as per child.
Daily reads bugs solved.

Daily Reads bugs solved

---

app/assets/translations/appOfflineData/getDataToStore.ts
app/screens/home/bottomTabs/Articles.tsx

article search issue solved

---

app/components/homeScreen/DailyReads.tsx
app/localization/initI18next.ts
app/screens/localization/CountrySelection.tsx

- Daily read bug on child taxanomy change solved.
- Language selection on app start based on device language.
- Taxonomy issue on back solved.
- Back issue on walkthrough solved.

Bugs solved

---

app/screens/home/bottomTabs/Articles.tsx

scrolling distortion issue

---

app/components/ActivitiesCategories.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/Icon.tsx
app/components/shared/ModalPopupStyle.tsx
app/screens/ChildImportSetup.tsx
app/screens/ChildSetup.tsx
app/screens/growth/AddNewChildHeight.tsx
app/screens/growth/AddNewChildWeight.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/growth/AllChildgrowthMeasures.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/bottomTabs/Articles.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

Import UI design, Fixed UI clickable area issues, games filter area increased,

Import UI design, Fixed UI clickable area issues

---

app/services/childCRUD.ts

changes for  last taxonomy id only param 0 added

changes for  last taxonomy id only param 0 added

---

app/screens/PrivacyPolicy.tsx
app/screens/home/ChildProfile.tsx

add expecting child navigation
privacy policy back navigation

add expecting child navigation privacy policy back navigation

---

app/components/LoadingScreenComponent.tsx
app/screens/LoadingScreen.tsx

- unicef static logo condition added

unicef static logo condition added

---

app/components/LoadingScreenComponent.tsx

- Logo issue on 1st loading solved

Logo issue solved

---

app/screens/home/bottomTabs/Activities.tsx

Milestone link added

---

app/screens/home/bottomTabs/Activities.tsx

Design change

---

app/components/shared/ShareFavButtons.tsx

Detailsscreen issue

---

app/screens/home/bottomTabs/Activities.tsx

- childmilestone updated data issue on 1st load solved
- Track milestone click area increased.

Milestone issue

---

app/components/FavActivities.tsx
app/components/FavArticles.tsx

- Favourite offline data issue solved

Favourite offline issue

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYbe.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/assets/translations/appOfflineData/apiConstants.ts
app/navigation/AppNavigation.tsx
app/redux/sagaMiddleware/saga.ts
app/screens/LoadingScreen.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

- Force Update api called on Home screen.
- Related changes in loading and saga files.
- String file updated for alert pop up

Force Update implementation

---

app/screens/home/bottomTabs/Home.tsx

Weekly update button uncommented

Weekly update button uncommented

---

app/components/ChildDate.tsx
app/navigation/AppNavigation.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetup.tsx
app/screens/home/bottomTabs/Activities.tsx
app/services/interpretationService.ts

ui fixes+minur bug fixes for date selection

ui fixes+minur bug fixes for date selection

---

app/screens/AddSiblingData.tsx

addsibling space reduced

---

app/screens/home/bottomTabs/Home.tsx

weekly testing picker issue solved and commented

weekly testing picker issue solved and commented

---

app/navigation/AppNavigation.tsx
app/screens/EditParentDetails.tsx

userRelationToParent as success fixed
_screen_opened

userRelationToParent as success fixed _screen_opened

---

app/screens/home/SettingScreen.tsx

icon replaced

---

app/screens/home/SettingScreen.tsx

text changed

---

app/screens/home/ChatBot.tsx

- Learn more link condition changed
- style object removed

Learn more link condition changed

---

app/screens/AddExpectingChildProfile.tsx
app/screens/CustomDrawerContent.tsx
app/screens/EditParentDetails.tsx
app/screens/growth/AddNewChildHeight.tsx
app/screens/growth/AddNewChildWeight.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/growth/AllChildgrowthMeasures.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/ChatBot.tsx
app/screens/home/ChildProfile.tsx
app/screens/home/DetailsScreen.tsx
app/screens/home/EditChildProfile.tsx
app/screens/localization/CountrySelection.tsx
app/screens/localization/LanguageSelection.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

- Made RTL changes for arrow icons

Made RTL changes for arrow icons

---

app/screens/localization/CountryLanguageConfirmation.tsx
app/screens/localization/LanguageSelection.tsx

added timeout for rtl in ios

---

app/screens/home/ChatBot.tsx
app/screens/home/SupportChat.tsx
app/services/commonApiService.ts

- Chatbot username issue solved
- Chatbot strings issue on language change solved.

Chatbot username issue solved

---

android/a03a6bdea0091aea32e1b35b90a7294c9f04e3dd
app/components/shared/ArticlesStyle.tsx
app/components/shared/SupportChatStyle.tsx
app/components/shared/TextInputML.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/AddSiblingData.tsx
app/screens/ChildSetup.tsx
app/screens/EditParentDetails.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/ChatBot.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/SupportChat.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/services/ScrollingButtonMenu.js

- Created Textinput component for multilingual.
- Changed agebracket icons for multilingual
- Solved chatbot crash issue in release mode.
- Minor other changes.

RTL changes and Chatbot crash issue

---

app/assets/translations/appOfflineData/apiConstants.ts
app/screens/Terms.tsx
app/screens/home/SupportChat.tsx
app/services/Utils.ts
app/services/periodicSync.ts

- Faqs pinned api call
- ImageBackground change in Chatbot

Faqs pinned api call and Imagebackground change

---

app/screens/home/DetailsScreen.tsx

- Changes for video article on detail screen

Changes for video article

---

app/assets/translations/appOfflineData/apiConstants.ts
app/screens/Terms.tsx
app/services/Utils.ts
app/services/periodicSync.ts

- Faq Pinned api call uncommented and tested

Faq Pinned api call

---

app/services/LoadableImage.tsx
app/services/RenderImage.tsx

changes for embedded loadable image ios

changes for embedded loadable image ios

---

android/app/src/main/AndroidManifest.xml
app/assets/translations/appOfflineData/apiConstants.ts
app/navigation/AppNavigation.tsx
app/screens/vaccination/AddReminder.tsx
app/services/LoadableImage.tsx
ios/ParentBuddyApp/ParentBuddyApp.entitlements

bug solving + function name changed

bug solving + function name changed

---

app/screens/LoadingScreen.tsx
app/services/commonApiService.ts
app/types/env.d.ts
package-lock.json
package.json

- React native keep awake plugin added.
- Implemented same on Loading screen.

Keep Awake plugin added

---

app/assets/translations/appOfflineData/apiConstants.ts
ios/ParentBuddyApp/ParentBuddyApp.entitlements

tesmobility entitlements & share pointed to tesmobility

tesmobility entitlements & share pointed to tesmobility

---

app/screens/home/SettingScreen.tsx

changes for error type added

---

app/screens/home/bottomTabs/Home.tsx

Datepicker commented

---

app/redux/sagaMiddleware/saga.ts
app/screens/LoadingScreen.tsx
app/services/commonApiService.ts

- Solved switch off internet in between loading screen issue

Loading screen issue

---

android/app/build.gradle
app/assets/translations/appConstants/ru.ts
app/assets/translations/appOfflineData/apiConstants.ts
app/screens/localization/LanguageSelection.tsx

Global lang pop up changes

---

app/assets/translations/appConstants/ALsq.ts
app/assets/translations/appConstants/BGbg.ts
app/assets/translations/appConstants/BYru.ts
app/assets/translations/appConstants/GRel.ts
app/assets/translations/appConstants/KGky.ts
app/assets/translations/appConstants/KGru.ts
app/assets/translations/appConstants/MEcnr.ts
app/assets/translations/appConstants/MKmk.ts
app/assets/translations/appConstants/MKsq.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/RSsr.ts
app/assets/translations/appConstants/TJru.ts
app/assets/translations/appConstants/TJtg.ts
app/assets/translations/appConstants/UZru.ts
app/assets/translations/appConstants/UZuz.ts
app/assets/translations/appConstants/XKrs.ts
app/assets/translations/appConstants/XKsq.ts
app/assets/translations/appConstants/en.ts
app/assets/translations/appConstants/ru.ts

changes for strings

---

app/assets/translations/appConstants/BYbe.ts

change for belarussin

---

app/components/homeScreen/DailyReads.tsx
app/components/shared/ShareFavButtons.tsx

changes for shared link

---

app/assets/translations/appOfflineData/getDataToStore.ts
app/screens/home/ChatBot.tsx
app/screens/home/SupportChat.tsx

- Offline English data condition for faqs in state variable condition removed
- If no faqs, new option added in Chatbot Screen with No data message

Chatbot changes

---

app/assets/translations/appConstants/GRarb.ts
app/assets/translations/appConstants/GRda.ts
app/assets/translations/appConstants/RSen.ts
app/assets/translations/appConstants/en.ts

changess for downloadAllPopupTitle,downloadAllPopupText key

changess for downloadAllPopupTitle,downloadAllPopupText key

---

app/screens/home/Notifications.tsx

notification changes on category click

notification changes on category click

---

app/components/growth/GrowthChart.tsx

tooltip changes added svg element in android and normal view in ios

tooltip changes added svg element in android and normal view in ios

---

app/screens/home/Aboutus.tsx

about us scroll changes

---

app/components/shared/TrackMilestoneView.tsx
app/screens/home/bottomTabs/Activities.tsx
app/services/Utils.ts

- articles details no space issue between tags solved
- suggested activities title space increased if no premature tag
- Track milestone click issue from Fav screen solved

UAT Bud fixes

---

android/app/build.gradle
app/screens/home/EditChildProfile.tsx
app/services/MediaPicker.ts
app/services/childCRUD.ts

gallery and camera message on second time+name trim

gallery and camera message on second time+name trim

---

app/components/growth/GrowthChart.tsx

growthchart flex 1 due to space

growthchart flex 1 due to space

---

app/screens/home/bottomTabs/ChildDevelopment.tsx

question hide if milestone reaches 100

question hide if milestone reaches 100

---

app/services/Utils.ts

child premature set as it is coming from file

child premature set as it is coming from file

---

app/screens/home/bottomTabs/Home.tsx

- Survey api call added on Home screen whenever app opens

Survey api call added

---

app/assets/translations/appOfflineData/apiConstants.ts
app/components/growth/ChartHeightForAge.tsx
app/components/growth/ChartWeightForHeight.tsx
app/screens/PrivacyPolicy.tsx
app/screens/home/Aboutus.tsx
app/screens/home/Childgrowth.tsx
app/screens/home/DetailsScreen.tsx
babel.config.js
metro.config.js
package-lock.json
package.json
tsconfig.json

- Solved embedded video issues.Added a plugin and changes.
- Made changes for hiding chart summary if measurements old.

Embedded video and growth changes

---

app/navigation/AppNavigation.tsx
package-lock.json
package.json

- Firebase Notification module added
- Alert shown on Foreground notification

Firebase Notification module added

---

android/app/src/xk/AndroidManifest.xml
app/assets/translations/appOfflineData/apiConstants.ts

constants change

---

app/assets/data/bebbo/localization.ts

changes for ukraine position

---

app/assets/data/bebbo/localization.ts
app/assets/data/xk/localization.ts
app/components/NotificationItem.tsx
app/components/homeScreen/BabyNotification.tsx
app/redux/reducers/index.ts
app/redux/reducers/localizationSlice.ts
app/screens/home/Childgrowth.tsx
app/services/childCRUD.ts

changes for pluralshow addition

changes for pluralshow addition

---

app/components/growth/ChartWeightForHeight.tsx
app/components/shared/RelatedArticles.tsx
app/services/interpretationService.ts

- Growth issue solved checked if flag is enabled

Growth issue solved

---

app/assets/translations/appConstants/bebbo/ALsq.ts
app/assets/translations/appConstants/bebbo/BGbg.ts
app/assets/translations/appConstants/bebbo/BYbe.ts
app/assets/translations/appConstants/bebbo/BYru.ts
app/assets/translations/appConstants/bebbo/GRel.ts
app/assets/translations/appConstants/bebbo/KGky.ts
app/assets/translations/appConstants/bebbo/KGru.ts
app/assets/translations/appConstants/bebbo/MEcnr.ts
app/assets/translations/appConstants/bebbo/MKmk.ts
app/assets/translations/appConstants/bebbo/MKsq.ts
app/assets/translations/appConstants/bebbo/RSsr.ts
app/assets/translations/appConstants/bebbo/TJru.ts
app/assets/translations/appConstants/bebbo/TJtg.ts
app/assets/translations/appConstants/bebbo/UZru.ts
app/assets/translations/appConstants/bebbo/UZuz.ts
app/assets/translations/appConstants/xk/XKrs.ts
app/assets/translations/appConstants/xk/XKsq.ts
ios/ParentBuddyApp/AppDelegate.m

changes for string files

---

app/components/ChildDate.tsx
app/screens/AddExpectingChildProfile.tsx
app/services/childCRUD.ts

changes for date changes

---

app/components/ChildDate.tsx
app/screens/AddExpectingChildProfile.tsx
app/services/childCRUD.ts

removed date field changes

---

app/assets/translations/appConstants/bebbo/ru.ts

russian changes

---

app/assets/translations/appConstants/bebbo/uk.ts

uk changes

---

app/assets/translations/appConstants/bebbo/ALsq.ts
app/assets/translations/appConstants/bebbo/BGbg.ts
app/assets/translations/appConstants/bebbo/BYbe.ts
app/assets/translations/appConstants/bebbo/BYru.ts
app/assets/translations/appConstants/bebbo/GRarb.ts
app/assets/translations/appConstants/bebbo/GRda.ts
app/assets/translations/appConstants/bebbo/GRel.ts
app/assets/translations/appConstants/bebbo/KGky.ts
app/assets/translations/appConstants/bebbo/KGru.ts
app/assets/translations/appConstants/bebbo/MEcnr.ts
app/assets/translations/appConstants/bebbo/MKmk.ts
app/assets/translations/appConstants/bebbo/MKsq.ts
app/assets/translations/appConstants/bebbo/RSen.ts
app/assets/translations/appConstants/bebbo/RSsr.ts
app/assets/translations/appConstants/bebbo/TJru.ts
app/assets/translations/appConstants/bebbo/TJtg.ts
app/assets/translations/appConstants/bebbo/UZru.ts
app/assets/translations/appConstants/bebbo/UZuz.ts
app/assets/translations/appConstants/bebbo/en.ts
app/assets/translations/appConstants/bebbo/ru.ts
app/assets/translations/appConstants/bebbo/uk.ts
app/components/HeaderNotiIcon.tsx
app/components/healthChekup/UpcomingHealthCheckup.tsx
app/components/vaccination/tabs/UpcomingVaccines.tsx
app/screens/vaccination/AddReminder.tsx
app/services/Utils.ts
app/services/notificationService.ts

- New date columns added after import code.
- Solved notification creation issue for expected child on import.Changed condition in service file.
- Added new strings where required.
- Solved datetime issue for 2nd reminder notification

Notification issues solved

---

app/components/homeScreen/DailyHomeNotification.tsx

- Dailyhomemessages crash issue solved

Dailyhomemessages crash issue

---

app/assets/translations/appOfflineData/bebbo/ActivitiesData.ts
app/assets/translations/appOfflineData/bebbo/healthCheckupsData.ts
app/assets/translations/appOfflineData/bebbo/taxonomies.ts
app/assets/translations/appOfflineData/bebbo/vaccineData.ts

changes for mk-sq in health-checkup,vaccineData in russian

changes for mk-sq in health-checkup,vaccineData in russian

---

app/assets/translations/appConstants/bebbo/uk.ts

changes for uk

---

app/screens/home/bottomTabs/Home.tsx
app/services/commonApiService.ts

- Home weekly datepicker commented
- Alert msg testing text commented.

Testing code commented

---

ios/InfoPlist_Xk/sq-XK.lproj/InfoPlist.strings
ios/InfoPlist_Xk/sr-Latn-XK.lproj/InfoPlist.strings

changes app name

---

app/screens/home/Notifications.tsx

- Notification last item issue solved added padding

Notification last item issue

---

app/screens/home/Notifications.tsx

- Notification pop up issue solved

Notification pop up issue

---

app/components/homeScreen/DailyReads.tsx
app/components/shared/ShareFavButtons.tsx
app/screens/CustomDrawerContent.tsx

changes for url with languagecode

changes for url with languagecode

---

app/assets/translations/appOfflineData/apiConstants.ts
app/services/commonApiService.ts
app/services/periodicSync.ts

- added conditions for datetime obj empty val
- solved update issue when new build update on old build

New build old build update issue

---

android/app/build.gradle

Foleja version updated

---

android/app/build.gradle
app/screens/CustomDrawerContent.tsx
app/screens/home/Notifications.tsx
app/services/Utils.ts

- import issue with reminders in a child solved.
- Foleja dev version changed
- Like Foleja links added
- Notification log commented

Bug fixes import

---

app/screens/CustomDrawerContent.tsx

menu changes

---

android/app/build.gradle

build version change

---

app/screens/home/SettingScreen.tsx
app/services/commonApiService.ts

- Local notification cleared on country change and after import
- enable/disable notification setting issue with local notification solved

Local notification issues solved

---

app/components/HeaderBabyMenu.tsx
app/components/shared/Icon.tsx
app/screens/home/ChildProfile.tsx

changes for icon

---

app/services/notificationService.ts

notification crash condition added

notification crash condition added

---

app/assets/data/bebbo/localization.ts

- luxon locale for Uzbek and Tajik russian changed for onboarding issue

luxon locale for Uzbek and Tajik russian changed

---

android/app/build.gradle

Build version changed

---

android/app/build.gradle
app/components/shared/RelatedArticles.tsx
app/components/shared/RelatedVideoArticles.tsx
app/screens/CustomDrawerContent.tsx
app/screens/home/bottomTabs/Articles.tsx

- Solved related videos reload issue on click of save.
- Added usememo wherever required
- Changed build gradle version.

Related video reload issue

---

app/components/HeaderNotiIcon.tsx
app/components/homeScreen/ChildInfo.tsx
app/redux/reducers/index.ts
app/redux/reducers/notificationSlice.ts
app/screens/ChildImportSetup.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/SettingScreen.tsx
app/screens/home/bottomTabs/Home.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/services/LocalNotifications.js
app/services/backup.tsx
app/services/childCRUD.ts
app/services/commonApiService.ts
app/services/notificationService.ts

- Added some store variables for local notifications
- Added function to create local notifications for specified child
- Added function to create , edit or cancel local notifications based on conditions
- Set local notification creation tag to true when importing, country language change, add child. edit child, on measurement updates, settings toggle flags.
- Generate unique random numbers for local notifications except for reminders
- Create all types of local notifications based on age brackets
- Added badge count as 1 by default
-

Local notification implementation

---

android/app/build.gradle
app/components/HeaderNotiIcon.tsx
app/components/homeScreen/ChildInfo.tsx
app/services/childCRUD.ts
app/services/notificationService.ts
app/services/periodicSync.ts

- Gradle version changed
- Added reminder and local notification deletion code on child delete
- Made changes for multiple notification generated for long age period when adding a new child.
- Logs commented

Multiple notification for large age bracket on child add hidden

---

android/app/build.gradle
app/services/backup.tsx
app/services/commonApiService.ts
app/services/notificationService.ts

- Local notification dispatch removed from backup.tsx as in common function for import.
- Cancelling Local notification commented from common as present in creation function.
- Solved 5 days before issue for CD noti 2
- Solved 3 months period monthly notification missing issue.

Local notification related changes

---

app/services/notificationService.ts

- Changed notification time to 7.00pm

Changed notification time to 7.00pm

---

app/components/ChildDate.tsx
app/components/shared/ChildSetupStyle.tsx
app/components/shared/FormPrematureContainer.tsx
app/types/types.ts

1.child info poup added in child birth date 
2.child birth date validation changed from 71 months to 72 months

Childinfo popup

---

android/app/build.gradle
app/assets/translations/appConstants/xk/XKsq.ts

- Foleja String changes
- Build version changed

Foleja Changes

---

android/build.gradle
app/components/HeaderNotiIcon.tsx
app/components/growth/LastChildMeasure.tsx
app/redux/reducers/notificationSlice.ts
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/services/childCRUD.ts
app/services/healthCheckupService.ts
package-lock.json

- Optimised code for Save issue
- Commented logs
- Disabled save button in all 4 tools
- Added mavencentral call in gradle as jcenter call has issues.

Tools save issue

---

app/screens/ChildImportSetup.tsx

change for child import setup

---

app/navigation/AppNavigation.tsx

deleted notification coming on relaunch app solved

deleted notification coming on relaunch app solved

---

app/components/shared/FormPrematureContainer.tsx
app/screens/ChildSetup.tsx

import ui changes

---

app/assets/data/firebaseEvents.ts
app/screens/CustomDrawerContent.tsx
app/services/childCRUD.ts

added articleCategory

---

app/assets/data/firebaseEvents.ts
app/screens/CustomDrawerContent.tsx

DONATE_OPENED event added

---

app/screens/home/bottomTabs/Home.tsx

notification popup coming on onboarding issue solved

notification popup coming on onboarding issue solved

---

app/components/shared/RelatedArticles.tsx
app/components/shared/RelatedVideoArticles.tsx
app/screens/home/DetailsScreen.tsx

changes for related video articles show if coming from home

changes for related video articles show if coming from home

---

app/assets/translations/appConstants/xk/XKrs.ts

changes for foleja build

---

android/app/build.gradle
app/services/Utils.ts

changes for date issue

---

app/services/commonApiService.ts

notification regenerate

---

app/components/ChildDate.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/growth/AddNewChildgrowth.tsx
app/screens/healthCheckup/AddChildHealthCheckup.tsx
app/screens/home/bottomTabs/Home.tsx
app/screens/vaccination/AddChildVaccination.tsx
app/screens/vaccination/AddReminder.tsx

work on Story ID 165039 - change the date picker design for android

work on Android date picker design changes

---

app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Articles.tsx

Work on Improve search results for articles and highlight word on details screen

Work on Story ID - 168504 : Improve Search results of Articles

---

app/screens/growth/AddNewChildWeight.tsx

Work on story ID: 169568 - weight measurement should allow up to 33 kg

Weight measurement should allow up to 33 kg

---

app/screens/home/bottomTabs/ChildDevelopment.tsx

work on story Id: 169567 -  child Development UI changes

Work on Child Development UI changes

---

app/screens/localization/CountrySelection.tsx

changes in countrylist from onboarding

changes in countrylist from onboarding

---

app/components/homeScreen/AdviceAndArticles.tsx
app/components/homeScreen/ChildMilestones.tsx
app/components/homeScreen/PlayingTogether.tsx

work on story id: 169571, Home Page UI changes

Home page UI changes

---

.eslintrc.json
.prettierrc.js
app/database/config/dataDbConfig.ts
app/database/schema/ActivitiesSchema.ts
app/database/schema/ArticleActivityViewSchema.ts
app/database/schema/ArticleSchema.ts
app/screens/home/DetailsScreen.tsx
app/screens/home/bottomTabs/Articles.tsx

work on daily reads suggestions ehnhancement

Feat - Daily Reads suggetions Enhancement

---

app/assets/data/firebaseEvents.ts
app/assets/translations/appOfflineData/apiConstants.ts
app/database/config/dataDbConfig.ts
app/database/schema/ActivitySearchHistorySchema.ts
app/screens/AddSiblingData.tsx
app/screens/home/bottomTabs/Activities.tsx
app/screens/home/bottomTabs/Articles.tsx

- Add search functionality to game
- Advice should be filter by age period

Add search game and advice should be filter by age period

---

app/navigation/AppNavigation.tsx
app/screens/AddExpectingChildProfile.tsx
app/screens/Terms.tsx
app/screens/home/EditChildProfile.tsx
app/screens/home/Notifications.tsx

- Add expecting child profile issue
- Fix home screen delay
- Notification screen scroll change for iOS
- Terms screen scroll changes
- Update child profile gender change

Fix - Bug fixing for latest bugs

---

app/screens/ChildSetup.tsx
app/screens/home/SettingScreen.tsx
app/services/backup.tsx

Import issue fixed for Android

Import issue fixed for Android

---

app/screens/home/SettingScreen.tsx

Added try/catch for state.SelectedCountry

Update the SettingScreen.tsx file

---

app/components/HeaderNotiIcon.tsx
app/database/dbquery/userRealmCommon.ts
app/redux/reducers/utilsSlice.ts
app/services/Utils.ts
app/services/backup.tsx
app/services/childCRUD.ts

The files are reverted due to PR 980 so that App got crashed for Android, we have updated the file.

App crashed for Android issue fixed
